server:
  port: 8088
jwt:
  secret: minhasenha
  expiration: 3600

spring:
  jpa:
    database: default
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sample2
    username: sample
    password: sample
    platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasources:
    -
      name: db1
      url: jdbc:postgresql://localhost:5432/sample
      username: sample
      password: sample
      driver-class-name: org.postgresql.Driver
    -
      name: db2
      url: jdbc:postgresql://localhost:5432/sample2
      username: sample
      password: sample
      driver-class-name: org.postgresql.Driver

    #  database:
    #    driverClassName: org.postgresql.Driver
    #  datasource:
    #    url: jdbc:postgresql://localhost:5432/sample
    #    username: sample
    #    password: sample
    #    platform: org.hibernate.dialect.PostgreSQL9Dialect
